### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by SimonPrinz** [SimonPrinz/mega-cmd#1]
- [ ] check for session at container start instead of trying to login
- [ ] use own (mega) user
- [ ] use volume for /home/<user>/.megaCmd (currently /root/.megaCmd)
